### PR TITLE
Feat/movie streaming

### PR DESCRIPTION
**Pull request by 1337Impact**

### CODE REVIEW

**Comment by zenon0777** [comment]
Please resolve the conflicts : always pull for changes, from main branch

**Comment by 1337Impact** [comment]
> Please resolve the conflicts : always pull for changes, from main branch

on it boss

**Comment by zenon0777** [comment]
Good boy, keep up!

**Review by zenon0777 — COMMENTED** [review]
Mohammed we now working on getting torrent file or magnet url using other provider. Is your features gonna work fine if we pass other torrent url or file

**Review by zenon0777 — APPROVED** [review]

**Comment by 1337Impact** [comment]
yes yes

**Pull request merged**
